### ISSUE TITLE
DNS leaks on Windows 10

### ISSUE THREAD

**Issue by ghost** [cryptostorm/cryptostorm_client_configuration_files#11]
As described [here](https://medium.com/@ValdikSS/beware-of-windows-10-dns-resolver-and-dns-leaks-5bc5bfb4e3f1), the config files should include an extra option: _block-outside-dns_

> Plugin functionality has been integrated in OpenVPN 2.3.9. Use _block-outside-dns_ option.

Otherwise Windows 10 is leaking the DNS requests.

**Comment by df-cryptostorm** [comment]
I was against adding that option at first because if the client is using OpenVPN < 2.3.9 it would result in a fatal error. Now that I think about it though, that's really only a problem for people using the Linux configs on certain embedded devices (routers, etc.) where it's difficult to upgrade OpenVPN. Nobody on Windows should be using an older OpenVPN, so I think I'll go ahead and add block-outside-dns just for the windows configs. DNS leaks usually aren't a problem on Linux anyways.
