### ISSUE TITLE
Error: too many 'remote' options (cstorm_Dynamic, mac)

### ISSUE THREAD

**Issue by FYI5** [cryptostorm/cryptostorm_client_configuration_files#14]
Tunnelblick doesn't accept more than 64 'remote' options in the .ovpn file. I can't add new nodes like Berlin and Canada to the cstorm_Dynamic.ovpn without getting this error in the log file. Connection fails because of this error.

Proposed solution: 
Only two 'remote' options for each node (currently four 'remote' options for each node)

Current:
remote linux-frankfurt.cryptostorm.net 443 udp
remote linux-frankfurt.cryptostorm.nu 443 udp
remote linux-frankfurt.cryptostorm.org 443 udp
remote linux-frankfurt.cstorm.pw 443 udp
remote etc.

Proposed solution:
remote linux-frankfurt.cryptostorm.net 443 udp
remote linux-frankfurt.cryptostorm.nu 443 udp
remote etc.

**Comment by FYI5** [comment]
Looks like it's a limitation of OpenVPN.

Reference: https://groups.google.com/forum/#!topic/tunnelblick-discuss/MSkP6BUIHm0

**Comment by michamilz** [comment]
gentle reminder :)

**Comment by df-cryptostorm** [comment]
Whoops, forgot about this. There's really no point in these 'dynamic' configs since there's the 'smoothed' ones that do the same thing. So I just removed all the 'dynamic' ones and changed the 'smoothed' ones to 'balancer' since that's more accurate. 

Looks like the mac config dir never had a 'smoothed' config though, so mac people probably didn't know about it or the balancers. 
Well there's one now - https://github.com/cryptostorm/cryptostorm_client_configuration_files/blob/master/mac/cstorm_Balancer.ovpn

If someone still wants to connect to specific nodes, they could just use that node/cluster's corresponding config. If you want a pool of your favorite nodes in one config, you can add the remote lines yourself :-P
If you don't care which one you connect to, the new 'balancer' (old 'smoothed') configs would be the ones to use.
