### ISSUE TITLE
London TCP/UDP

### ISSUE THREAD

**Issue by ghost** [cryptostorm/cryptostorm_client_configuration_files#9]
London TCP and UDP aren't working, will not connect. Connecting to everything else fine. Saw the comment to remove the from the conf, is UK somewhere where cryptostorm isn't running VPN any more?

**Comment by df-cryptostorm** [comment]
Whoops, meant to delete the London configs here too when I removed them from the dynamic confs. Needed a `git add . -A` instead of just `git add .`.

The London node is down at the moment due to a combination of abuse complaints and RAM failures. I'm still working with OneProvider (London's ISP) to try and get the server restored, but since I'm not sure if/when that will happen, I went ahead and removed the config +DNS entries.

**Comment by df-cryptostorm** [comment]
This particular London server went down permanently. We're getting a replacement somewhere in the UK pretty soon.
